[workspace]
resolver = "2"
members = [
    "fiolet-core",
]

[workspace.package]
version = "0.1.3"
authors = ["Adrian Maliszewski"]
edition = "2021"
license = "MIT"
repository = "https://github.com/maliszewskiadrian/FINAL_FIOLET_ENGINE"

[profile.release]
# Optymalizacje pod maksymalne bezpieczeństwo i szybkość
opt-level = 3
panic = "abort" # Wymagane dla bezpieczeństwa (zatrzymuje proces natychmiast)
lto = true      # Link Time Optimization (lepsza wydajność)
codegen-units = 1
strip = true    # Usuwa symbole debugowania (mniejszy binarny "ślad")
